- src/macos/AdapterBaseMacOS.mm
threw exception using llvm on macos
> Added missing classname to SimpleBLE::advertising_data_t

- CMakeLists.txt
- include/simpleble_c/adapter.h
- include/simpleble_c/peripheral.h
- include/simpleble_c/simpleble.h
@Andrey1994 I added a setting to CMake that should automatically export all symbols from the shared libraries. Can you tell me if this works for you?
> Added auto export feature for Windows DLLs

- src/linux/PeripheralBase.cpp
On Linux, when reading various Characteristic's values, the value was either empty or out of date. Fixed this by using the appropriate function from SimpleBluez.
> Read the characteristic value from the peer instead of the cache (Linux)

- src/linux/PeripheralBase.cpp
On Linux, the battery service (UUID 0x180f) is filtered out if the Bluez battery plugin is loaded (Bluez version >= 5.48). This seems to be standard behaviour on Ubuntu 20.04 and probably other distributions as well.
This PR emulates the battery service by using the Battery1 interface of Bluez. Requires related [PR in SimpleBLE](https://github.com/OpenBluetoothToolbox/SimpleBluez/pull/3).
Functionality of this workaround was tested on Ubuntu 20.04, Bluez version 5.53, with activated and deactivated battery plugin (`example_read` and `example_notify`).
Notable differences in behaviour of the emulated battery service:
- Only the battery percentage characteristic is emulated (UUID 0x2a19)
- On percentage characteristic read, the current value provided by the Battery1 interface is returned. …
> Emulate unavailable battery service if Bluez Battery1 interface is found

- utils/build_lib.ps1
Building shared lib under Windows with utils\build_lib.bat only worked for 64 bit (x64) architecture due to missing "-A $WINDOWS_ARCH" parameter on cmake command line calls in build_lib.ps1 for lib build and example build. Now "build_lib.bat -a x86" builds properly for 32 bit Windows target.
> Building shared libs under Windows only worked for 64 bit architecture.

- utils/build_lib.sh
build_lib.sh assumes bash is /usr/local/bin/bash but on Ubuntu it is /usr/bin/bash. Change shebang of build_lib.sh from #!/usr/local/bin/bash to #!/usr/bin/env bash, which will find bash on any Linux installation.
> build_lib.sh does not build on Ubuntu 20.04LTS

- simpleble/CMakeLists.txt
Now the relocatable package created by CMake/install can contain more lib versions (release/debug/minsizerel/relwithdebinfo) not only the latest one
Tested on win10
> CMake change to support more lib versions (release/debug/minsizerel/relwithdebinfo) in the created relocatable package

- docs/changelog.rst
- simpleble/include/simpleble/Logging.h
- simpleble/src/Logging.cpp
- simpleble/src/LoggingInternal.h
The capitalized convention was too prone to conflicts from other system libraries, this one should work better.
> Change log level convention

- docs/simpleble/usage.rst
When trying to build SimpleBLE on Fedora 36, I was running into the `dbus-1 not found` error. I found that installing `dbus-devel` solved this. I added this to the docs.
> Add section for RPM-based distros

- simpleble/CMakeLists.txt
Add compile option `/utf-8` for Microsoft Visual Studio.
This solves #177 when compiling with any locale different than English.
> Set source and executable character sets to utf-8.

- simplersble/src/lib.rs
This fixes the Adapter::scan_is_active() binding to return the underlying boolean value
> fix scan_is_active

- simpleble/src/backends/macos/AdapterBase.mm
- simpleble/src/backends/macos/AdapterBaseMacOS.h
- simpleble/src/backends/macos/AdapterBaseMacOS.mm
- simplersble/src/lib.rs
Currently, the Adapter::address() function returns a MAC address with all 0s. This does not match peripheral addresses on MacOS (UUIDs), and it cannot be used e.g. to index adapters in a hash map. This commit gives adapters a UUID on MacOS and returns the UUID string in Adapter::address(). It also changes Adapter::identifier() to include the UUID string.
> Give adapters a unique address on MacOS

- simpleble/src/backends/macos/AdapterBaseMacOS.mm
Caching based on the adapter UUID should be supported and this currently doesn't work if there is a need to reinitialize the adapter.
> MacOS Adapter should have a constant UUID

- simpleble/src/backends/macos/PeripheralBaseMacOS.mm
Allow waiting for service discovery as long as the device remains connected.
> Remove service discovery timeout

- simpleble/src/backends/macos/AdapterBase.mm
(see title). The implication of this issue is that stale devices can be surfaced by `scan_get_results`, since `peripherals_` is never cleared.
> [MacOS] Use only seen peripherals when retrieving scan results

- simpleble/src/backends/macos/PeripheralBaseMacOS.h
- simpleble/src/backends/macos/PeripheralBaseMacOS.mm
Corebluetooth docs: `Attempts to connect to a peripheral don't time out`. SimpleBLE should expose a connectWithTimeout method to handle this flow gracefully for the consumer.
> [MacOS] Add timeout to connect

- docs/changelog.rst
- simpleble/src/backends/macos/PeripheralBaseMacOS.mm
- simpleble/src/backends/macos/Utils.h
- simpleble/src/backends/macos/Utils.mm
This should fix the issue outlined in: https://github.com/OpenBluetoothToolbox/SimpleBLE/issues/277
> Fixed issue in MacOS when notifying from standard UUIDs

- .github/workflows/ci_linux.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_main.yml
- .github/workflows/ci_py_release.yml
- .github/workflows/ci_python.yml
- .github/workflows/ci_python_publish.yml
- .github/workflows/ci_release.yaml
- .github/workflows/ci_release_cpp.yml
- .github/workflows/ci_release_python.yml
- .github/workflows/ci_release_rust.yml
- .github/workflows/ci_wheels.yml
- .github/workflows/ci_windows.yml
- docs/extras.rst
- scripts/check_version.sh
- setup.py
- **Automate Python Development Releases:**  
Set the development version number based on the count of commits since the last bump of the `VERSION` file (see `setup.py`).
- **Version Number Sanity Checks:**  
Added checks in `scripts/check_version.sh` to ensure version consistency across the repository.
- **Refined Release Workflow:**  
Improved the release process by updating broken action versions and merging all workflows into a single `ci_release.yml`.
- **Rust Publishing:**  
Implemented Rust publishing in the release workflow. Ensure the `CRATES_IO_API_TOKEN` secret is configured in the repository environment.
- **Improve Test Build Runtime:**  
Reduced build time by compiling only the static versions of all libraries. Both static and shared libraries will still be built for …
> Fix release workflow and some CI improvements

- .github/workflows/ci_linux.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_main.yml
- .github/workflows/ci_python.yml
- .github/workflows/ci_python_publish.yml
- .github/workflows/ci_release_cpp.yml
- .github/workflows/ci_release_python.yml
- .github/workflows/ci_wheels.yml
- CI was not fetching tags when using _actions/checkout_, resulting in incorrect tagging of the development release
- Wheels were not being published because Twine was missing in _ci_python_publish.yml_
- Upgraded macOS runner from version 12 to 14. Check [this issue](https://github.com/actions/runner-images/issues/10721)
- Fix linux libraries path filter not being set for runs in main branch
> Fix Python development releases, upgrade macOS runner

- MANIFEST.in
- setup.py
Problem: 
- The Python dev versioning logic assumed that `setup.py` was being executed inside a Git repository, causing an exception when building from source outside of Git
- A missing file in the `MANIFEST` caused the build to fail
Changes in this PR:
- Update `setup.py` to modify the `VERSION` file content during source distribution generation, appending the dev version if needed. This ensures consistency with the version in published wheels
- Updates `setup.py` to fall back on the `VERSION` file content if Git commands fail
- Adds the missing files to the `MANIFEST`
> Fix python source distributions builds

- simpleble/src/backends/macos/PeripheralBaseMacOS.mm
This pull request removes what appears to be an unnecessary debug log that floods the console when _Write Without Response_ is used.
> Remove unnesserary macOS debug log

- docs/simpleble/tutorial.rst
Fixed link paths for the usage.rst file and cpp/c examples in response to #393
> Fix link paths in tutorial.rst
